name: flutter_fit_utils_config
description: "A flutter package to easily manage configurations. This package is part of the flutter_fit_utils environement."
version: 1.0.3
homepage: https://pub.dev/packages/flutter_fit_utils_config
repository: https://github.com/Vaistudio-dev/flutter_fit_utils_config
issue_tracker: https://github.com/Vaistudio-dev/flutter_fit_utils_config/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - configuration
  - remote-config

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_remote_config: ^5.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0