name: flutter_fit_utils_config
description: "Set of pre-built and customizable configuration utilities for Flutter apps."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_fit_utils:
    git:
      url: https://github.com/s0punk/flutter_fit_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: